---
- hosts: all
  gather_facts: no
  tasks:
  - debug: msg='no'

- hosts: all
  gather_facts: no
  tasks:
  - debug: msg='create only'
  tags:
  - create


- hosts: all
  gather_facts: no
  tasks:
  - debug: msg='create,modify'
  tags:
  - create
  - modify

- hosts: all
  gather_facts: no
  tasks:
  - debug: msg='modify'
  tags:
  - modify

- hosts: all
  gather_facts: no
  tasks:
  - debug: msg='destroy'
  tags:
  - destroy


