---
- hosts: all
  tasks:
  - debug: var=hostvars[inventory_hostname]
#  tags:
#  - always

- hosts: all
  tasks:
  - debug: msg='create only'
  tags:
  - create

- hosts: all
  tasks:
  - debug: msg='create,modify'
  tags:
  - create
  - update

- hosts: all
  tasks:
  - debug: msg='modify'
  tags:
  - update

- hosts: all
  tasks:
  - debug: msg='destroy'
  tags:
  - destroy


